# Generated by Django 3.1.6 on 2021-03-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Manufacturer', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'MAKEUP'), ('F', 'FASHION_WEARS'), ('E', 'Electronics'), ('FO', 'FOODS')], max_length=2)),
                ('Image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('Pradesh', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
