# Generated by Django 3.1.6 on 2021-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_orderplaced_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'MAKEUP'), ('C', 'Cream'), ('P', 'Pants'), ('BS', 'Brush'), ('G', 'Gents'), ('L', 'Ladies'), ('T', 'Shirts')], max_length=2),
        ),
    ]
