# Generated by Django 3.1.6 on 2021-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Purchased_Date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Pradesh',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
