# Generated by Django 3.1.7 on 2021-04-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210408_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='Pradesh',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='area',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='place',
        ),
    ]
