# Generated by Django 3.1.6 on 2021-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210409_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/userimage/login.jpg', upload_to='static/userimage'),
        ),
    ]
